model: gpt-4o-mini
edit_format: udiff
auto_commits: true
git: true
detect_renames: true
map_tokens: 3000
use_git_grep: true
files:
  - app.py
  - config.py
  - config/*.*
  - handlers/**/*.py
  - services/**/*.py
  - templates/**/*.html
  - static/**/*.*
  - Dockerfile*
  - compose.yml
  - nginx.conf
  - supervisord.conf
test_cmd: []

