# Backup Manager Configuration
global_settings:
  dest_host: "192.168.1.252"  # Your NUC IP
  rsync_path: "/usr/bin/rsync"
  time_path: "/usr/bin/time"
  notification:
    telegram_token: "your_token_here"
    telegram_chat_id: "your_id_here"

backup_jobs:
  audiobooks:
    source: "/var/lib/docker/volumes/yetiData/_data/media/audiobooks/"
    includes: []
    excludes: []
    enabled: true
    schedule: "daily"
  
  movies:
    source: "/var/lib/docker/volumes/yetiData/_data/media/movies/"
    includes: []
    excludes: []
    enabled: true
    schedule: "weekly"
  
  photos:
    source: "/var/lib/docker/volumes/yetiData/_data/media/family.photos/"
    includes: []
    excludes: []
    enabled: true
    schedule: "daily"
  
  services:
    source: "/var/lib/docker/volumes/"
    includes:
      - "haugene**"
      - "lidarr**"
      - "murmur**"
      - "pihole**"
      - "portainer**"
      - "prowlarr**"
      - "radarr**"
      - "sabnzbd**"
      - "sonarr**"
      - "wg-easy**"
    excludes:
      - "*"
    enabled: true
    schedule: "daily"
  
  videos:
    source: "/var/lib/docker/volumes/yetiData/_data/media/home.videos/"
    includes: []
    excludes: []
    enabled: true
    schedule: "weekly"

backup_logs: {}
