name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'handlers/**'
      - 'services/**'
      - 'templates/**'
      - 'static/**'
      - 'config/**'
      - '*.py'
      - '*.conf'
      - 'requirements.txt'
      - 'favicon.ico'
  workflow_dispatch:

concurrency:
  group: highball-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CalVer and short SHA
        id: vars
        run: |
          echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          provenance: true
          sbom: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha }}

